services:
  csrf-engine:
    build:
      context: ./csrf-engine
      dockerfile: Dockerfile
    ports:
      - "5001:8000"
    env_file:
      - .env
    environment:
      - PORT=5001
      - HOST=0.0.0.0
    networks:
      - test-case-generation

  lfi-engine:
    build:
      context: ./lfi-engine
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    volumes:
      - ./lfi-engine:/app
    environment:
      - FLASK_ENV=development 
      - HOST=localhost
      - PORT=5000
    networks:
      - test-case-generation

  traversal-engine:
    build: 
      context: ./traversal-engine
      dockerfile: Dockerfile
    command: ['php', '-S', "0.0.0.0:8080", "/app/main_server.php"]
    ports:
      - "5003:8080"
    volumes:
      - ./traversal-engine/src:/app/src
      - ./traversal-engine/logs:/app/logs
      - ./traversal-engine/outputs:/app/outputs
      - ./traversal-engine/tmp:/tmp
    env_file:
      - .env
    environment:
      - XDEBUG_MODE=coverage,debug
    networks:
      - test-case-generation
  
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: ['npm', 'run', 'dev']
    ports:
      - "8080:8080"
      - "3000:3000"
      - "3001:3001"
    networks:
      - test-case-generation
    env_file:
      - .env
    depends_on:
      - csrf-engine
      - lfi-engine
      - traversal-engine

networks:
  test-case-generation:

volumes:
  logs: